services:
  prometheus:
    image: prom/prometheus:v2.54.1
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
  grafana:
    image: grafana/grafana:11.2.1
    volumes:
      - ./__DATA__/grafana_data:/var/lib/grafana:rw
      #- ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards:rw
      #- ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources:rw
    environment:
      - GF_SECURITY_ADMIN_USER=${ADMIN_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin}
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Editor
      - GF_SERVER_HTTP_PORT=4000
      - GF_USERS_ALLOW_SIGN_UP=false
    restart: unless-stopped
    expose:
      - 4000
    ports:
      - 4000:4000
    network_mode: host
    user: "472"
    labels:
      org.label-schema.group: "monitoring"

  couchdb:
    image: couchdb:3.1.1
    environment:
      COUCHDB_USER: admin
      COUCHDB_PASSWORD: password
    volumes:
      - couchdb_data:/opt/couchdb/data
      - couchdb_config:/opt/couchdb/etc/local.d
      - couchdb_log:/opt/couchdb/var/log
    ports:
      - "5984:5984"
      - "6984:6984"
  app:
    build:
      context: ../
    ports:
      - "3500:3500"
    restart: always
    volumes:
      - ../:/app
    environment:
      - FLASK_ENV=production
    depends_on:
      - couchdb
      - prometheus
      - grafana

volumes:
  couchdb_data:
  couchdb_config:
  couchdb_log:
